name: Kingsword09 Standard Library Docs

on:
  push:
    tags:
      - "@kingsword09/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Generate Docs
        run: deno task docs
      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build from artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs